# Generated by Django 5.1.7 on 2025-03-12 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_track_alter_course_id_course_track'),
        ('trainee_app', '0002_trainee_course_alter_trainee_id_alter_trainee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_app.track'),
        ),
    ]
